### ISSUE TITLE
Numerous minor frontend fixes

### ISSUE THREAD

**Issue by zdavis** [castiron/manifold-marketing#115]
Blake,

You did a really excellent job on the frontend implementation. I have a list of very minor tweaks I'd like made. If any of these are less minor than I think they are, let's discuss—I don't want these to eat up too much time.

- [x] HOME: Change to primary navigation color: default is black, active and hover is the teal color.
- [x] HOME: Annotate icon on HP doens't render well; line weight is off on the bottom horizontal line
- [x] HOME: Integrate icon appears to be missing on the HP
- [x] HOME: Can we reduce the bottom padding on the "Manifold Hearts Modern Devices" blade?
- [x] HOME: Roughly double the space between the two columns in the newsletter signup blade
- [x] HOME: Bump up the font size of the footer links by 1-2px
- [x] HOME: Make the footer github icon a bit larger; feels unbalanced against the twitter icon
- [x] HOME: Remove the search field from the footer
- [x] HOME: Read more links under "Building Manifold" should have a dark gray hover state
- [x] HOME/MOBILE: Font on the "Menu" link is incorrect
- [x] HOME/MOBILE: Font on "Close" link in mobile nav is incorrect
- [x] HOME/MOBILE: Reduce the space between icon and text in "Do it yourself" blade
- [x] HOME/MOBILE: Bump up the copy font size (.copy-secondary, and perhaps others) by 1-2px.
- [x] HOME/MOBILE: All of the blades need a little bit more bottom-padding
- [x] HOME/MOBILE: Headers in "Building Manifold" section have matching heights (flexbox?), which shouldn't be the case on mobile.
- [x] HOME/MOBILE: Missing "Home" link in mobile primary navigation
- [x] LEARN: Missing hover state on reader/author/publisher icons
- [x] LEARN: Interior page newsletter signup form should right align with manifold logo; ideally, text doesn't wrap.
- [x] LEARN/MOBILE: Feature category icon vertical alignment is off
- [x] LEARN/MOBILE: Features are too crowded. I'm fine with going to one or two columns, if that's easier
- [x] LEARN/MOBILE: Let's hide or significantly reduce the side of the partner logos on mobile
- [x] COMMUNITY: Too much top-margin on Slack blade. Maybe just generate a new slack logo image without padding to solve it?
- [x] RESOURCES: Incorrect font on FAQs
- [x] RESOURCES/MOBILE: Let's hide the icons on the support blade in mobile and tighten up the spacing.
- [x] SERVICES: Incorrect body font on the "Ready to Start Digitall Publishing?" blade
- [x] DOCUMENTATION/MOBILE: Previous/Next links often wrap on mobile. We could hide or truncate the labels, or perhaps always break to two lines. Use best judgement.
- [x] DOCUMENTATION/MOBILE: I wasn't able to get the TOC navigation to work on mobile.

best,
Zach

**Comment by zdavis** [comment]
Some additional tweaks from Lael (not duplicative of my list)

[Manifold Marketing - Lael Feedback v1.1.pdf](https://github.com/castiron/manifold-marketing/files/1589898/Manifold.Marketing.-.Lael.Feedback.v1.1.pdf)

**Comment by kylepratuch** [comment]
Blake, I discovered this while working on the contact forms:

- [ ] Only "Send" text is clickable on submit button
