### ISSUE TITLE
Unclosed comment in markdown causing broken HTML

### ISSUE THREAD

**Issue by blnkt** [castiron/manifold-marketing#119]
There's a comment in this markdown copy (you can see it on the right in the inspector) that I think, because it does not get properly closed, is breaking the markup that follows it (including the pagination and site footer).  This is on the Copyright and Permissions page:  `http://manifold-marketing.lvh/docs/contents/authors/rights`

<img width="939" alt="screen shot 2017-12-28 at 11 48 02 am" src="https://user-images.githubusercontent.com/8166060/34421613-3598a268-ebc5-11e7-876c-3c013d46e286.png">

**Comment by blnkt** [comment]
I'm not able to reproduce this on staging so it may have to do with differences in the content or differences introduced in addressing #115.

**Comment by zdavis** [comment]
On staging, the documentation is automatically updated from the docs repo when it changes (using a github webhook). In your local instance, you should be able to go into october settings -> static microsites and press the "pull repo" button to update your docs from the remote repo.
