### ISSUE TITLE
Confirm contact forms work on staging and production hosts

### ISSUE THREAD

**Issue by zdavis** [castiron/manifold-marketing#125]
Run a jenkins release on staging first.

**Comment by rclarkburns** [comment]
@kylepratuch Can you confirm mails are being sent on staging?

**Comment by kylepratuch** [comment]
@rclarkburns It works! 👍

**Comment by rclarkburns** [comment]
@kylepratuch Can you please test this now on production? manifoldapp.org it should be accessible to you if your on the CIC network.

**Comment by zdavis** [comment]
It seems this is done, as Terence confirmed receipt of emails.
