### ISSUE TITLE
Javascript throws numerous console warnings when elements are missing

### ISSUE THREAD

**Issue by zdavis** [castiron/manifold-marketing#126]
The javascript on this site is written in such a way that it assumes many DOM elements are present at all times. However, the `classburger` module logs a message when elements aren't present. This warning is superfluous, and we should either check for the presence of dom elements before initializing javascript around them (better solution, IMO), or remove the warning.

This may be an issue elsewhere. I noticed this morning that video related code breaks javascript site-wide if no video player is present. I applied a quick conditional fix, but this part of the javascript doesn't feel very clean to me. Shouldn't lines 31-45 of manifold-theme.js be moved to its own module, to keep that main file simple and clear?

**Comment by naomiyaki** [comment]
On it!
